import {Component, Input, SimpleChanges} from '@angular/core';
import {Attendee} from '../../services/attendee.service';

@Component({
  selector: 'attendee',
  templateUrl: 'attendee.html'
})
export class AttendeeComponent {

  @Input() attendee: Attendee = new Attendee;
  attendance_count_suffix: string = 'th';
  country_code: string;
  country_codes: any = new Map<string, string>();

  constructor() {
    this.country_codes.set('Afghanistan', 'af');
    // this.country_codes.set('Åland Islands', 'ax');
    this.country_codes.set('Albania', 'al');
    this.country_codes.set('Algeria', 'dz');
    this.country_codes.set('American Samoa', 'as');
    this.country_codes.set('Andorra', 'ad');
    this.country_codes.set('Angola', 'ao');
    this.country_codes.set('Anguilla', 'ai');
    // this.country_codes.set('Antarctica', 'aq');
    // this.country_codes.set('Antigua and Barbuda', 'ag');
    this.country_codes.set('Argentina', 'ar');
    this.country_codes.set('Armenia', 'am');
    this.country_codes.set('Aruba', 'aw');
    this.country_codes.set('Australia', 'au');
    this.country_codes.set('Austria', 'at');
    this.country_codes.set('Azerbaijan', 'az');
    this.country_codes.set('Bahrain', 'bh');
    this.country_codes.set('Bahamas', 'bs');
    this.country_codes.set('Bangladesh', 'bd');
    this.country_codes.set('Barbados', 'bb');
    this.country_codes.set('Belarus', 'by');
    this.country_codes.set('Belgium', 'be');
    this.country_codes.set('Belize', 'bz');
    this.country_codes.set('Benin', 'bj');
    this.country_codes.set('Bermuda', 'bm');
    this.country_codes.set('Bhutan', 'bt');
    this.country_codes.set('Bolivia', 'bo');
    this.country_codes.set('Bonaire', 'bq');
    this.country_codes.set('Bosnia and Herzegovina', 'ba');
    this.country_codes.set('Botswana', 'bw');
    this.country_codes.set('Bouvet Island', 'bv');
    this.country_codes.set('Brazil', 'br');
    // this.country_codes.set('British Indian Ocean Territory', 'io');
    this.country_codes.set('Brunei Darussalam', 'bn');
    this.country_codes.set('Bulgaria', 'bg');
    this.country_codes.set('Burkina Faso', 'bf');
    this.country_codes.set('Burundi', 'bi');
    this.country_codes.set('Cambodia', 'kh');
    this.country_codes.set('Cameroon', 'cm');
    this.country_codes.set('Canada', 'ca');
    this.country_codes.set('Cape Verde', 'cv');
    // this.country_codes.set('Cayman Islands', 'ky');
    // this.country_codes.set('Central African Republic', 'cf');
    this.country_codes.set('Chad', 'td');
    this.country_codes.set('Chile', 'cl');
    this.country_codes.set('China', 'cn');
    // this.country_codes.set('Christmas Island', 'cx');
    // this.country_codes.set('Cocos (Keeling) Islands', 'cc');
    this.country_codes.set('Colombia', 'co');
    this.country_codes.set('Comoros', 'km');
    // this.country_codes.set('Congo', 'cg');
    // this.country_codes.set('Democratic Republic of the Congo', 'cd');
    // this.country_codes.set('Cook Islands', 'ck');
    this.country_codes.set('Costa Rica', 'cr');
    // this.country_codes.set('Côte d\'Ivoire', 'ci');
    this.country_codes.set('Croatia', 'hr');
    this.country_codes.set('Cuba', 'cu');
    this.country_codes.set('Curaçao', 'cw');
    this.country_codes.set('Cyprus', 'cy');
    this.country_codes.set('Czech Republic', 'cz');
    this.country_codes.set('Denmark', 'dk');
    this.country_codes.set('Djibouti', 'dj');
    this.country_codes.set('Dominica', 'dm');
    this.country_codes.set('Dominican Republic', 'do');
    this.country_codes.set('Ecuador', 'ec');
    this.country_codes.set('Egypt', 'eg');
    this.country_codes.set('El Salvador', 'sv');
    this.country_codes.set('Equatorial Guinea', 'gq');
    this.country_codes.set('Eritrea', 'er');
    this.country_codes.set('Estonia', 'ee');
    this.country_codes.set('Ethiopia', 'et');
    // this.country_codes.set('Falkland Islands', 'fk');
    // this.country_codes.set('Faroe Islands', 'fo');
    // this.country_codes.set('Fiji', 'fj');
    this.country_codes.set('Finland', 'fi');
    this.country_codes.set('France', 'fr');
    this.country_codes.set('French Guiana', 'gf');
    this.country_codes.set('French Polynesia', 'pf');
    // this.country_codes.set('French Southern Territories', 'tf');
    this.country_codes.set('Gabon', 'ga');
    this.country_codes.set('Gambia', 'gm');
    this.country_codes.set('Georgia', 'ge');
    this.country_codes.set('Germany', 'de');
    this.country_codes.set('Ghana', 'gh');
    this.country_codes.set('Gibraltar', 'gi');
    this.country_codes.set('Greece', 'gr');
    this.country_codes.set('Greenland', 'gl');
    this.country_codes.set('Grenada', 'gd');
    // this.country_codes.set('Guadeloupe', 'gp');
    this.country_codes.set('Guam', 'gu');
    this.country_codes.set('Guatemala', 'gt');
    this.country_codes.set('Guernsey', 'gg');
    this.country_codes.set('Guinea', 'gn');
    this.country_codes.set('Guinea-Bissau', 'gw');
    this.country_codes.set('Guyana', 'gy');
    this.country_codes.set('Haiti', 'ht');
    // this.country_codes.set('Heard Island and McDonald Islands', 'hm');
    // this.country_codes.set('Vatican City', 'va');
    this.country_codes.set('Honduras', 'hn');
    this.country_codes.set('Hong Kong', 'hk');
    this.country_codes.set('Hungary', 'hu');
    this.country_codes.set('Iceland', 'is');
    this.country_codes.set('India', 'in');
    this.country_codes.set('Indonesia', 'id');
    this.country_codes.set('Iran', 'ir');
    this.country_codes.set('Iraq', 'iq');
    this.country_codes.set('Ireland', 'ie');
    // this.country_codes.set('Isle of Man', 'im');
    this.country_codes.set('Israel', 'il');
    this.country_codes.set('Italy', 'it');
    this.country_codes.set('Jamaica', 'jm');
    this.country_codes.set('Japan', 'jp');
    this.country_codes.set('Jersey', 'je');
    this.country_codes.set('Jordan', 'jo');
    this.country_codes.set('Kazakhstan', 'kz');
    this.country_codes.set('Kenya', 'ke');
    this.country_codes.set('Kiribati', 'ki');
    this.country_codes.set('South Korea', 'kr');
    this.country_codes.set('Kuwait', 'kw');
    // this.country_codes.set('Kyrgyzstan', 'kg');
    this.country_codes.set('Latvia', 'lv');
    this.country_codes.set('Lebanon', 'lb');
    this.country_codes.set('Lesotho', 'ls');
    this.country_codes.set('Liberia', 'lr');
    this.country_codes.set('Libya', 'ly');
    // this.country_codes.set('Liechtenstein', 'li');
    this.country_codes.set('Lithuania', 'lt');
    this.country_codes.set('Luxembourg', 'lu');
    this.country_codes.set('Macao', 'mo');
    this.country_codes.set('Macedonia', 'mk');
    this.country_codes.set('Madagascar', 'mg');
    this.country_codes.set('Malawi', 'mw');
    this.country_codes.set('Malaysia', 'my');
    this.country_codes.set('Maldives', 'mv');
    this.country_codes.set('Mali', 'ml');
    this.country_codes.set('Malta', 'mt');
    this.country_codes.set('Marshall Islands', 'mh');
    // this.country_codes.set('Martinique', 'mq');
    this.country_codes.set('Mauritania', 'mr');
    this.country_codes.set('Mauritius', 'mu');
    this.country_codes.set('Mayotte', 'yt');
    this.country_codes.set('Mexico', 'mx');
    this.country_codes.set('Micronesia', 'fm');
    this.country_codes.set('Moldova', 'md');
    // this.country_codes.set('Monaco', 'mc');
    this.country_codes.set('Mongolia', 'mn');
    this.country_codes.set('Montenegro', 'me');
    this.country_codes.set('Montserrat', 'ms');
    this.country_codes.set('Morocco', 'ma');
    this.country_codes.set('Mozambique', 'mz');
    this.country_codes.set('Myanmar', 'mm');
    this.country_codes.set('Namibia', 'na');
    this.country_codes.set('Nauru', 'nr');
    this.country_codes.set('Nepal', 'np');
    this.country_codes.set('Netherlands', 'nl');
    this.country_codes.set('New Caledonia', 'nc');
    this.country_codes.set('New Zealand', 'nz');
    this.country_codes.set('Nicaragua', 'ni');
    this.country_codes.set('Niger', 'ne');
    this.country_codes.set('Nigeria', 'ng');
    this.country_codes.set('Niue', 'nu');
    // this.country_codes.set('Norfolk Island', 'nf');
    // this.country_codes.set('Northern Mariana Islands', 'mp');
    this.country_codes.set('Norway', 'no');
    this.country_codes.set('Oman', 'om');
    this.country_codes.set('Pakistan', 'pk');
    this.country_codes.set('Palau', 'pw');
    this.country_codes.set('Palestine', 'ps');
    this.country_codes.set('Panama', 'pa');
    this.country_codes.set('Papua New Guinea', 'pg');
    this.country_codes.set('Paraguay', 'py');
    this.country_codes.set('Peru', 'pe');
    this.country_codes.set('Philippines', 'ph');
    this.country_codes.set('Pitcairn', 'pn');
    this.country_codes.set('Poland', 'pl');
    this.country_codes.set('Portugal', 'pt');
    this.country_codes.set('Puerto Rico', 'pr');
    this.country_codes.set('Qatar', 'qa');
    this.country_codes.set('Réunion', 're');
    this.country_codes.set('Romania', 'ro');
    this.country_codes.set('Russia', 'ru');
    this.country_codes.set('Rwanda', 'rw');
    this.country_codes.set('Saint Barthélemy', 'bl');
    // this.country_codes.set('Saint Helena', 'sh');
    // this.country_codes.set('Saint Kitts and Nevis', 'kn');
    // this.country_codes.set('Saint Lucia', 'lc');
    // this.country_codes.set('Saint Martin', 'mf');
    // this.country_codes.set('Saint Pierre and Miquelon', 'pm');
    // this.country_codes.set('Saint Vincent and the Grenadines', 'vc');
    this.country_codes.set('Samoa', 'ws');
    this.country_codes.set('San Marino', 'sm');
    this.country_codes.set('Sao Tome and Principe', 'st');
    this.country_codes.set('Saudi Arabia', 'sa');
    this.country_codes.set('Senegal', 'sn');
    this.country_codes.set('Serbia', 'rs');
    this.country_codes.set('Seychelles', 'sc');
    this.country_codes.set('Sierra Leone', 'sl');
    this.country_codes.set('Singapore', 'sg');
    // this.country_codes.set('Sint Maarten', 'sx');
    this.country_codes.set('Slovakia', 'sk');
    this.country_codes.set('Slovenia', 'si');
    this.country_codes.set('Solomon Islands', 'sb');
    this.country_codes.set('Somalia', 'so');
    this.country_codes.set('South Africa', 'za');
    // this.country_codes.set('South Georgia and the South Sandwich Islands', 'gs');
    this.country_codes.set('South Sudan', 'ss');
    this.country_codes.set('Spain', 'es');
    this.country_codes.set('Sri Lanka', 'lk');
    this.country_codes.set('Sudan', 'sd');
    this.country_codes.set('Suriname', 'sr');
    // this.country_codes.set('Svalbard and Jan Mayen', 'sj');
    this.country_codes.set('Swaziland', 'sz');
    this.country_codes.set('Sweden', 'se');
    this.country_codes.set('Switzerland', 'ch');
    this.country_codes.set('Syria', 'sy');
    this.country_codes.set('Taiwan', 'tw');
    this.country_codes.set('Tajikistan', 'tj');
    this.country_codes.set('Tanzania', 'tz');
    this.country_codes.set('Thailand', 'th');
    // this.country_codes.set('Timor-Leste', 'tl');
    this.country_codes.set('Togo', 'tg');
    this.country_codes.set('Tokelau', 'tk');
    this.country_codes.set('Tonga', 'to');
    this.country_codes.set('Trinidad and Tobago', 'tt');
    this.country_codes.set('Tunisia', 'tn');
    this.country_codes.set('Turkey', 'tr');
    this.country_codes.set('Turkmenistan', 'tm');
    // this.country_codes.set('Turks and Caicos Islands', 'tc');
    this.country_codes.set('Tuvalu', 'tv');
    this.country_codes.set('Uganda', 'ug');
    this.country_codes.set('Ukraine', 'ua');
    this.country_codes.set('United Arab Emirates', 'ae');
    this.country_codes.set('United Kingdom', 'gb');
    this.country_codes.set('United States', 'us');
    // this.country_codes.set('United States Minor Outlying Islands', 'um');
    this.country_codes.set('Uruguay', 'uy');
    this.country_codes.set('Uzbekistan', 'uz');
    this.country_codes.set('Vanuatu', 'vu');
    this.country_codes.set('Venezuela', 've');
    this.country_codes.set('Viet Nam', 'vn');
    this.country_codes.set('Virgin Islands, British', 'vg');
    this.country_codes.set('Virgin Islands, U.S.', 'vi');
    // this.country_codes.set('Wallis and Futuna', 'wf');
    this.country_codes.set('Western Sahara', 'eh');
    this.country_codes.set('Yemen', 'ye');
    this.country_codes.set('Zambia', 'zm');
    this.country_codes.set('Zimbabwe', 'zw');
  }

  ngOnChanges(changes: SimpleChanges) {
    if ((this.attendee.attendance_count + 1) % 10 == 1) {
      this.attendance_count_suffix = 'st'
    } else if ((this.attendee.attendance_count + 1) % 10 == 2) {
      this.attendance_count_suffix = 'nd'
    } else if ((this.attendee.attendance_count + 1) % 10 == 3) {
      this.attendance_count_suffix = 'rd'
    }
    this.country_code = this.country_codes.get(this.attendee.home_country);
  }
}
